---
# - name: "DotNet | Install DotNet using install script"
#   become: true
#   community.general.snap:
#     name:
#       - dotnet-sdk 
#     channel: 8.0
#     classic: true 
#     state: present
#
# - name: "DotNet | Install dotnet-outdated-tool"
#   ansible.builtin.shell: 
#     cmd: dotnet tool install --global dotnet-outdated-tool

- name: "DotNet | Install Dotnet using install script"
  vars:
    dotnet_runtime: dotnet
    dotnet_channel: 8.0
    dotnet_script_path: /tmp
    dotnet_installation_path: /home/{{ host_user }}
    # dotnet_dependencies:
    #   - libc6
    #   - libgcc1
    #   - libgssapi-krb5-2
    #   - libicu66
    #   - libssl1.1
    #   - libstdc++6
    #   - zlib1g

  block:

    - name : Make sure HTTPS is supported by apt
      apt:
        name: apt-transport-https
        state: latest
        update_cache: yes
      become: true

    # - name: Install dotnet dependencies #https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-2004#dependencies
    #   apt:
    #     name: "{{ dotnet_dependencies }}"
    #     state: latest
    #     update_cache: yes
    #   become: yes

    - name: Download MS dotnet-install script
      get_url:
        url: https://dot.net/v1/dotnet-install.sh
        dest: "{{ dotnet_script_path }}/dotnet-install.sh"
        force: true

    - name: Make dotnet-install script executable
      ansible.builtin.command: chmod +x "{{ dotnet_script_path }}/dotnet-install.sh"
      become_user: yes

    - name: Install dotnet
      ansible.builtin.shell:
        cmd: "{{ dotnet_script_path }}/dotnet-install.sh --channel {{ dotnet_channel }}"
          #cmd: "{{ dotnet_script_path }}/dotnet-install.sh --channel {{ dotnet_channel }} --runtime {{ dotnet_runtime }}"
        chdir: "{{ dotnet_installation_path  }}"

    - name: Cleanup dotnet-install files
      ansible.builtin.file:
        path: "{{ dotnet_script_path  }}/dotnet-install.sh"
        state: absent
