- name: "DotNet | Install DotNet using install script"
  become: true 
  block: 
    
    - name: "DotNet | Install dotnet dependencies"
      ansible.builtin.apt:
        name: apt-transport-https
        state: present

    - name: Install dotnet dependencies 
      become: true
      ansible.builtin.apt:
        name: "{{ dotnet_dependencies }}"
        state: present 
      debugger: on_failed

  vars:
    dotnet_runtime: dotnet
    dotnet_channel: 8.0
    dotnet_script_path: /tmp
    dotnet_installation_path: /home/{{ host_user }}
    dotnet_dependencies:
      - libc6
      - libgcc1
      - libgssapi-krb5-2
      - libicu66
      - libssl1.1
      - libstdc++6
      - zlib1g   
    # - name: Download MS dotnet-install script
    #   get_url:
    #     url: https://dot.net/v1/dotnet-install.sh
    #     dest: "{{ dotnet_script_path }}/dotnet-install.sh"
    #
    # - name: Make dotnet-install script executable
    #   ansible.builtin.command: chmod +x "{{ dotnet_script_path }}/dotnet-install.sh"
    #   become_user: yes
    #
    # - name: Install dotnet
    #   ansible.builtin.shell:
    #     cmd: "{{ dotnet_script_path }}/dotnet-install.sh --channel {{ dotnet_channel }} --runtime {{ dotnet_runtime }}"
    #     chdir: "{{ dotnet_installation_path  }}"
    #
    # - name: Cleanup dotnet-install files
    #   ansible.builtin.file:
    #     path: "{{ dotnet_script_path  }}/dotnet-install.sh"
    #     state: absent

