---
- name: "DotNet | Install DotNet using install script"
  become: true
  community.general.snap:
    name:
      - dotnet-sdk 
    channel: 8.0
    classic: true 
    state: present

- name: "DotNet | Install dotnet-outdated-tool"
  ansible.general.shell: 
  cmd: "dotnet tool install --global dotnet-outdated-tool"
