- name: "DotNet | Install Dotnet using Microsoft feeds"
  block:
    - name: Dotnet | Install dotnet repository
      ansible.builtin.apt_repository:
        repo: 'ppa:dotnet/backports'
      become: true
    - name: Dotnet | Install Dotnet 9 SDK and Runtime
      ansible.builtin.apt:
        name:
          - dotnet-sdk-9.0
          - dotnet-runtime-9.0
        state: present
      become: true
