---
- name: Rust | Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  become: true
  loop:
    - rustc
    - cargo

- name: Rust | Install cargo-watch
  ansible.builtin.shell: cargo install cargo-watch
