- hosts:  localhost
  connection: local
  gather_facts: no


  tasks:
    - name: "Git | Set user.name"
      community.general.git_config:
        name: user.name
        scope: global
        value: "{{ git_user_email }}"
