---
- name: Cleanup neovim downloaded tar
  ansible.builtin.file:
    path: "/tmp/nvim-linux64.tar.gz"
    state: absent
  become: true

- name: Remove extracted neovim directory
  ansible.builtin.file:
    path: /tmp/nvim-linux64
    state: absent
  become: true

