---
- name: "FZF | Uninstall APT fzf"
  ansible.builtin.apt:
    name: fzf
    state: absent
  become: true

- name: "FZF | Clone Latest Version"
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    depth: 1
    dest: "{{ ansible_user_dir }}/.fzf"
  notify: "Install FZF"

- name: "FZF | Clone the fzf-git"
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf-git.sh.git
    depth: 1
    dest: "{{ ansible_user_dir }}/fzf-git"
