---
- name: "Git | Install"
  ansible.builtin.apt:
    name:
      - git
    state: latest
  become: true

- name: "Git | Set diff.colorMoved"
  community.general.git_config:
    name: diff.colorMoved
    scope: global
    value: default

- name: "Git | Set fetch.prune"
  community.general.git_config:
    name: fetch.prune
    scope: global
    value: true

# git config --global --add url."git@github.com:".insteadOf "https://github.com/"
# - name: "Git | Set URL to SSH"
#   community.general.git_config:
#     name: URL
#     scope: global
#     value: "git@github.com"

- name: "Git | Set init.defaultBranch"
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main

- name: "Git | Set pull.rebase"
  community.general.git_config:
    name: pull.rebase
    scope: global
    value: true

- name: "Git | Set rebase.autoStash"
  community.general.git_config:
    name: rebase.autoStash
    scope: global
    value: true

- name: "Git | Set user.email"
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"
  no_log: true

- name: "Git | Set user.name"
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"

# Alias for add, commit and push in one command
- name: "Git | Set alias.cmp"
  community.general.git_config:
    name: alias.cmp
    scope: global
    value: "!f() { git add -A && git commit -m \"$@\" && git push; }; f"


- name: "Git | Set commit.gpgsign"
  community.general.git_config:
    name: commit.gpgsign
    scope: global
    value: true

- name: "Git | Set commit.gpgsign"
  community.general.git_config:
    name: gpg.program
    scope: global
    value: "/mnt/c/Program Files (x86)/GnuPG/bin/gpg.exe"

- name: "Git | Set tag.gpgsign"
  community.general.git_config:
    name: tag.gpgsign
    scope: global
    value: true

- name: "Git | Set user.signingkey"
  community.general.git_config:
    name: user.signingkey
    scope: global
    value: "{{ git_user_signingkey }}"

- name: "Git | Set core.pager"
  community.general.git_config:
    name: "core.pager"
    scope: global
    value: "delta"

- name: "Git | Set interactive.diffFilter"
  community.general.git_config:
    name: interactive.diffFilter
    scope: global
    value: "delta --color-only"

- name: "Git | Set delta.navigate"
  community.general.git_config:
    name: delta.navigate
    scope: global
    value: "true"

- name: "Git | Set delta.side-by-side"
  community.general.git_config:
    name: delta.side-by-side
    scope: global
    value: "true"

- name: "Git | merge.conflictstyle"
  community.general.git_config:
    name: merge.conflictstyle
    scope: global
    value: "diff3"
