---
- name: "Neovim | Dependencies"
  ansible.builtin.apt:
    name:
      - cmake
      - curl
      - pkg-config
      - libtool
      - unzip
      - ansible-lint
      - ripgrep
      - fzf
    state: present
  become: true

- name: "Neovim | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory


- name: "Neovim | Download Neovim appimsge"
  when:
    - ansible_host_environment_is_wsl
    - not win32yank_installed.stat.exists
  block:
    - name: Neovim - Download appimage
      ansible.builtin.get_url:
        url: https://github.com/neovim/neovim/releases/download/v0.9.5/nvim.appimage
        dest: /tmp/nvim-appimage
        mode: "0755"

    - name: Neovim | Copy neovim into path
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/nvim-appimage
        dest: /usr/local/bin/nvim
        mode: "0755"
        force: true
      become: true

    - name: Neovim | Remove tmp file
      ansible.builtin.file:
        path: /tmp/nvim-appimage
        state: absent

- name: "Neovim | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true

# - name: "Neovim | Copy init.lua"
#   ansible.builtin.copy:
#     dest: "{{ ansible_user_dir }}/.config/nvim/init.lua"
#     src: "init.lua"
#     mode: "0644"
#
# - name: "Neovim | Copy .luarc.json"
#   ansible.builtin.copy:
#     dest: "{{ ansible_user_dir }}/.config/nvim/.luarc.json"
#     src: ".luarc.json"
#     mode: "0644"
# - name: "Neovim | Copy modules"
#   ansible.builtin.copy:
#     dest: "{{ ansible_user_dir }}/.config/nvim/lua"
#     src: "lua/"
#     mode: "0644"
