---
- name: "Neovim | Dependencies"
  ansible.builtin.apt:
    name:
      - cmake
      - curl
      - pkg-config
      - libtool
      - unzip
      - ansible-lint
      - ripgrep
      - libfuse2
      - nodejs

    state: present
  become: true

- name: "Neovim | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory


- name: "Neovim | Download Neovim appimsge"
  block:
    - name: Neovim | Fetch latest release from GitHub API
      uri:
        url: "https://api.github.com/repos/neovim/neovim/releases/latest"
        return_content: yes
      register: github_response

    - name: Neovim | Parse latest release version
      set_fact:
        latest_version: "{{ github_response.json.tag_name }}"

    - name: Neovim | Get the download URL for the AppImage
      set_fact:
        appimage_url: "{{ github_response.json.assets | selectattr('name', 'search', 'nvim.appimage') | map(attribute='browser_download_url') | first }}"

    - name: Neovim | Download the latest Neovim AppImage
      get_url:
        url: "{{ appimage_url }}"
        dest: "/tmp/nvim.appimage"
        mode: '0755'

    - name: Neovim | Copy neovim into path
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/nvim.appimage
        dest: /usr/local/bin/nvim
        mode: "0755"
        force: true
      become: true

    - name: Neovim | Remove tmp file
      ansible.builtin.file:
        path: /tmp/nvim.appimage
        state: absent

- name: "Neovim | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true

# - name: "Neovim | Copy init.lua"
#   ansible.builtin.copy:
#     dest: "{{ ansible_user_dir }}/.config/nvim/init.lua"
#     src: "init.lua"
#     mode: "0644"
#
# - name: "Neovim | Copy .luarc.json"
#   ansible.builtin.copy:
#     dest: "{{ ansible_user_dir }}/.config/nvim/.luarc.json"
#     src: ".luarc.json"
#     mode: "0644"
# - name: "Neovim | Copy modules"
#   ansible.builtin.copy:
#     dest: "{{ ansible_user_dir }}/.config/nvim/lua"
#     src: "lua/"
#     mode: "0644"
