---
- name: "Neovim | Dependencies"
  ansible.builtin.apt:
    name:
      - cmake
      - curl
      - pkg-config
      - libtool
      - unzip
      - ansible-lint
      - ripgrep
      - fzf
    state: present
  become: true

- name: "Neovim | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory


- name: "Neovim | Download, extract Neovim appimsge"
  block:
    - name: "Neovim | Ensure clean download destination"
      ansible.builtin.file:
        path: "nvim-linux64.tar.gz"
        state: absent
      become: true

    - name: Neovim - Download appimage
      ansible.builtin.get_url:
        url: https://github.com/neovim/neovim/releases/download/v0.9.5/nvim-linux64.tar.gz
        dest: /tmp/nvim-linux64.tar.gz
        mode: "0755"
        force: true
      notify:
        - Cleanup neovim downloaded tar

    - name: "Neovim | Ensure clean extraction destination"
      ansible.builtin.file:
        path: "/tmp/nvim-linux64"
        state: absent
      become: true

    - name: "Neovim | Extract lazygit tar file"
      ansible.builtin.unarchive:
        src: "/tmp/nvim-linux64.tar.gz"
        dest: /tmp

    - name: "Neovim | Remove any current lazygit installations"
      ansible.builtin.file:
        path: /usr/local/bin/nvim
        state: absent
      become: true

    - name: "Neovim | Install lazygit"
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/nvim.linux64/nvim
        dest: /usr/local/bin/
        owner: "{{ host_user }}"
        group: "{{ host_user }}"
        force: true
        mode: "0755"
      become: true
      notify:
        - Remove extracted neovim directory

- name: "Neovim | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true

# - name: "Neovim | Copy init.lua"
#   ansible.builtin.copy:
#     dest: "{{ ansible_user_dir }}/.config/nvim/init.lua"
#     src: "init.lua"
#     mode: "0644"
#
# - name: "Neovim | Copy .luarc.json"
#   ansible.builtin.copy:
#     dest: "{{ ansible_user_dir }}/.config/nvim/.luarc.json"
#     src: ".luarc.json"
#     mode: "0644"
# - name: "Neovim | Copy modules"
#   ansible.builtin.copy:
#     dest: "{{ ansible_user_dir }}/.config/nvim/lua"
#     src: "lua/"
#     mode: "0644"
