---
- name: "bat | Install bat" 
  ansible.builtin.apt:
    name: bat
    state: present
  become: true

- name: "bat | Find batcat path"
  ansible.builtin.shell:
    cmd: which batcat
  register: batcat_path

- name: "fd | Create symlink to bat command"
  ansible.builtin.file:
    src: "{{ batcat_path.stdout }}"
    dest: "{{ ansible_user_dir }}/.local/bin/bat"
    state: link
    force: true
