---
- name: "bat | get deb file"
  ansible.builtin.get_url:
    url: "https://github.com/sharkdp/bat/releases/download/v0.24.0/bat_0.24.0_amd64.deb"
    dest: "{{ ansible_user_dir }}/bat.deb"
    #mode: "0755"
  notify: "Remove BATDEB"

- name: "bat | Install deb"
  apt:
    deb: "{{ ansible_user_dir }}/bat.deb"
  become: true

- name: "bat | Find bat config path"
  ansible.builtin.shell:
    cmd: bat --config-dir
  register: bat_config_dir
  
- name: "bat | Create the theme directory"
  ansible.builtin.file:
    path: "{{ bat_config_dir.stdout }}/themes"
    state: directory
    force: true
    mode: "0755"

- name: "bat | get tokio night theme"
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/sublime/tokyonight_night.tmTheme"
    dest: "{{ bat_config_dir.stdout }}/themes"
    mode: "0755"

- name: "bat | build cache"
  ansible.builtin.shell:
    cmd: bat cache --build

